import { type ComponentInstance } from "@/labs/types";

/**
 * BCD to Excess-3 Code Converter — 60-Column Long Breadboard Layout
 * -----------------------------------------------------------------------------
 * Implementation Equations:
 *   W = A + B(C + D)
 *   X = B ⊕ (C + D)
 *   Y = (C ⊕ D)'  = C ⊙ D
 *   Z = D'
 *
 * Intermediate Signals:
 *   T = C + D (generated by or_cd, shared by and_b_t and xor_x)
 *   B·T = B(C + D) (generated by and_b_t, fed into or_w)
 *
 * Logic Gates (all DIP-14 packages seated on row e, straddling centre gap):
 *   col 5..11  : or_cd   (74HC32, inputs C, D  → output T = C + D)
 *   col 13..19 : and_b_t (74HC08, inputs B, T  → output B·T)
 *   col 21..27 : or_w    (74HC32, inputs A, B·T→ output W)
 *   col 29..35 : xor_x   (74HC86, inputs B, T  → output X = B ⊕ T)
 *   col 37..43 : xor_cd  (74HC86, inputs C, D  → output C ⊕ D)
 *   col 45..51 : not_y   (74HC04, input C ⊕ D  → output Y = (C ⊕ D)')
 *   col 53..59 : not_z   (74HC04, input D      → output Z = D')
 *
 * Output Indicators (row h, directly beneath corresponding gates):
 *   col 21..26 : r_w (330 Ω) + led_w (Red,    W output / MSB)
 *   col 29..34 : r_x (330 Ω) + led_x (Yellow, X output)
 *   col 45..50 : r_y (330 Ω) + led_y (Green,  Y output)
 *   col 53..58 : r_z (330 Ω) + led_z (Blue,   Z output / LSB)
 */

export const components: ComponentInstance[] = [
  // ── Solderless Breadboard ──────────────────────────────────────────────────
  { id: "bb", type: "long-breadboard" },

  // ── Regulated DC Power Supply (+5 V trainer jack) ──────────────────────────
  {
    id: "psu",
    type: "dc-jack",
    mountedAt: { board: "bb", col: 1, row: "a" },
    terminals: [
      { board: "bb", rail: "vcc_top", col: 1 },
      { board: "bb", rail: "gnd_top", col: 1 },
    ],
  },
  {
    id: "w_rail_link",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_top", col: 59 },
    to: { board: "bb", rail: "vcc_bot", col: 59 },
  },

  // ── Logic Gate IC Packages (Row e) ─────────────────────────────────────────
  {
    id: "or_cd",
    type: "or-gate",
    mountedAt: { board: "bb", col: 5, row: "e" },
  },
  {
    id: "and_b_t",
    type: "and-gate",
    mountedAt: { board: "bb", col: 13, row: "e" },
  },
  {
    id: "or_w",
    type: "or-gate",
    mountedAt: { board: "bb", col: 21, row: "e" },
  },
  {
    id: "xor_x",
    type: "xor-gate",
    mountedAt: { board: "bb", col: 29, row: "e" },
  },
  {
    id: "xor_cd",
    type: "xor-gate",
    mountedAt: { board: "bb", col: 37, row: "e" },
  },
  {
    id: "not_y",
    type: "not-gate",
    mountedAt: { board: "bb", col: 45, row: "e" },
  },
  {
    id: "not_z",
    type: "not-gate",
    mountedAt: { board: "bb", col: 53, row: "e" },
  },

  // ── Gate IC Power Connections (VCC → bottom rail, GND → top rail) ──────────
  // or_cd
  {
    id: "w_vcc_or_cd",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 5 },
    to: { board: "bb", col: 5, row: "f" },
  },
  {
    id: "w_gnd_or_cd",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 11, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 11 },
  },

  // and_b_t
  {
    id: "w_vcc_and",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 13 },
    to: { board: "bb", col: 13, row: "f" },
  },
  {
    id: "w_gnd_and",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 19, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 19 },
  },

  // or_w
  {
    id: "w_vcc_or_w",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 21 },
    to: { board: "bb", col: 21, row: "f" },
  },
  {
    id: "w_gnd_or_w",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 27, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 27 },
  },

  // xor_x
  {
    id: "w_vcc_xor_x",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 29 },
    to: { board: "bb", col: 29, row: "f" },
  },
  {
    id: "w_gnd_xor_x",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 35, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 35 },
  },

  // xor_cd
  {
    id: "w_vcc_xor_cd",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 37 },
    to: { board: "bb", col: 37, row: "f" },
  },
  {
    id: "w_gnd_xor_cd",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 43, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 43 },
  },

  // not_y
  {
    id: "w_vcc_not_y",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 45 },
    to: { board: "bb", col: 45, row: "f" },
  },
  {
    id: "w_gnd_not_y",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 51, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 51 },
  },

  // not_z
  {
    id: "w_vcc_not_z",
    type: "wire",
    color: "purple",
    from: { board: "bb", rail: "vcc_bot", col: 53 },
    to: { board: "bb", col: 53, row: "f" },
  },
  {
    id: "w_gnd_not_z",
    type: "wire",
    color: "black",
    from: { board: "bb", col: 59, row: "e" },
    to: { board: "bb", rail: "gnd_top", col: 59 },
  },

  // ── Output Indicators (330 Ω Resistors + LEDs on Row h) ───────────────────
  // Bit W (MSB) — Red LED
  {
    id: "r_w",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 21, row: "h" },
  },
  {
    id: "led_w",
    type: "led",
    color: "red",
    mountedAt: { board: "bb", col: 25, row: "h" },
  },

  // Bit X — Yellow LED
  {
    id: "r_x",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 29, row: "h" },
  },
  {
    id: "led_x",
    type: "led",
    color: "yellow",
    mountedAt: { board: "bb", col: 33, row: "h" },
  },

  // Bit Y — Green LED
  {
    id: "r_y",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 45, row: "h" },
  },
  {
    id: "led_y",
    type: "led",
    color: "green",
    mountedAt: { board: "bb", col: 49, row: "h" },
  },

  // Bit Z (LSB) — Blue LED
  {
    id: "r_z",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 53, row: "h" },
  },
  {
    id: "led_z",
    type: "led",
    color: "blue",
    mountedAt: { board: "bb", col: 57, row: "h" },
  },

  // ── Output Drive Wires (Gate Y → Resistor → LED → GND rail) ───────────────
  // W Output Chain
  {
    id: "w_w_to_r",
    type: "wire",
    color: "red",
    from: { ic: "or_w", pin: "Y" },
    to: { component: "r_w", end: "p1" },
  },
  {
    id: "w_r_to_led_w",
    type: "wire",
    color: "red",
    from: { component: "r_w", end: "p2" },
    to: { led: "led_w", end: "anode" },
  },
  {
    id: "w_gnd_w",
    type: "wire",
    color: "black",
    from: { led: "led_w", end: "cathode" },
    to: { board: "bb", rail: "gnd_bot", col: 26 },
  },

  // X Output Chain
  {
    id: "w_x_to_r",
    type: "wire",
    color: "yellow",
    from: { ic: "xor_x", pin: "Y" },
    to: { component: "r_x", end: "p1" },
  },
  {
    id: "w_r_to_led_x",
    type: "wire",
    color: "yellow",
    from: { component: "r_x", end: "p2" },
    to: { led: "led_x", end: "anode" },
  },
  {
    id: "w_gnd_x",
    type: "wire",
    color: "black",
    from: { led: "led_x", end: "cathode" },
    to: { board: "bb", rail: "gnd_bot", col: 34 },
  },

  // Y Output Chain
  {
    id: "w_y_to_r",
    type: "wire",
    color: "green",
    from: { ic: "not_y", pin: "Y" },
    to: { component: "r_y", end: "p1" },
  },
  {
    id: "w_r_to_led_y",
    type: "wire",
    color: "green",
    from: { component: "r_y", end: "p2" },
    to: { led: "led_y", end: "anode" },
  },
  {
    id: "w_gnd_y",
    type: "wire",
    color: "black",
    from: { led: "led_y", end: "cathode" },
    to: { board: "bb", rail: "gnd_bot", col: 50 },
  },

  // Z Output Chain
  {
    id: "w_z_to_r",
    type: "wire",
    color: "blue",
    from: { ic: "not_z", pin: "Y" },
    to: { component: "r_z", end: "p1" },
  },
  {
    id: "w_r_to_led_z",
    type: "wire",
    color: "blue",
    from: { component: "r_z", end: "p2" },
    to: { led: "led_z", end: "anode" },
  },
  {
    id: "w_gnd_z",
    type: "wire",
    color: "black",
    from: { led: "led_z", end: "cathode" },
    to: { board: "bb", rail: "gnd_bot", col: 58 },
  },

  // ── Input Distribution Wires (A, B, C, D) ──────────────────────────────────
  // Input A (Red) → or_w.A
  {
    id: "w_a_or_w",
    type: "wire",
    color: "red",
    from: { board: "bb", col: 1, row: "a" },
    to: { ic: "or_w", pin: "A" },
  },

  // Input B (Orange) → and_b_t.A and xor_x.A
  {
    id: "w_b_and",
    type: "wire",
    color: "orange",
    from: { board: "bb", col: 2, row: "a" },
    to: { ic: "and_b_t", pin: "A" },
  },
  {
    id: "w_b_xor",
    type: "wire",
    color: "orange",
    from: { board: "bb", col: 2, row: "b" },
    to: { ic: "xor_x", pin: "A" },
  },

  // Input C (Blue) → or_cd.A and xor_cd.A
  {
    id: "w_c_or",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 3, row: "a" },
    to: { ic: "or_cd", pin: "A" },
  },
  {
    id: "w_c_xor",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 3, row: "b" },
    to: { ic: "xor_cd", pin: "A" },
  },

  // Input D (Green) → or_cd.B, xor_cd.B, and not_z.A
  {
    id: "w_d_or",
    type: "wire",
    color: "green",
    from: { board: "bb", col: 4, row: "a" },
    to: { ic: "or_cd", pin: "B" },
  },
  {
    id: "w_d_xor",
    type: "wire",
    color: "green",
    from: { board: "bb", col: 4, row: "b" },
    to: { ic: "xor_cd", pin: "B" },
  },
  {
    id: "w_d_not",
    type: "wire",
    color: "green",
    from: { board: "bb", col: 4, row: "c" },
    to: { ic: "not_z", pin: "A" },
  },

  // ── Internal Interconnect Wires (Cascaded logic stages) ────────────────────
  // T = C + D (or_cd.Y) → and_b_t.B
  {
    id: "w_or_cd_to_and",
    type: "wire",
    color: "white",
    from: { ic: "or_cd", pin: "Y" },
    to: { ic: "and_b_t", pin: "B" },
  },
  // T = C + D (or_cd.Y) → xor_x.B
  {
    id: "w_or_cd_to_xor",
    type: "wire",
    color: "white",
    from: { ic: "or_cd", pin: "Y" },
    to: { ic: "xor_x", pin: "B" },
  },
  // B·T (and_b_t.Y) → or_w.B
  {
    id: "w_and_to_or_w",
    type: "wire",
    color: "white",
    from: { ic: "and_b_t", pin: "Y" },
    to: { ic: "or_w", pin: "B" },
  },
  // C ⊕ D (xor_cd.Y) → not_y.A
  {
    id: "w_xor_cd_to_not_y",
    type: "wire",
    color: "white",
    from: { ic: "xor_cd", pin: "Y" },
    to: { ic: "not_y", pin: "A" },
  },
];
