import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Add resistors, LEDs, and wire outputs.",
  body: "Place 330 Ω resistors and LEDs for each output: Yellow LED (EQ) at col 22 row c; Red LED (GT) at col 22 row h; Green LED (LT) at col 25 row c. Wire each gate output through its resistor to LED anode. Connect all LED cathodes to GND rail.",
  show: [
    "bb",
    "xnor1",
    "not1",
    "and1",
    "not2",
    "and2",
    "w_a_xnor",
    "w_a_and1",
    "w_a_not2",
    "w_b_xnor",
    "w_b_not1",
    "w_b_and2",
    "w_notb_and1",
    "w_nota_and2",
    "r_eq",
    "r_gt",
    "r_lt",
    "led_eq",
    "led_gt",
    "led_lt",
    "w_xnor_req",
    "w_req_led",
    "w_eq_gnd",
    "w_and1_rgt",
    "w_rgt_led",
    "w_gt_gnd",
    "w_and2_rlt",
    "w_rlt_led",
    "w_lt_gnd",
  ],
  activeInputs: {
    A: 0,
    B: 0,
  },
};
