import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: A=1, B=1 → EQ=1.",
  body: "Set A=1, B=1. XNOR(1,1)=1 → yellow LED ON. GT and LT outputs are both LOW. Record all four test results in the observation table.",
  show: [
    "bb",
    "xnor1",
    "not1",
    "and1",
    "not2",
    "and2",
    "w_a_xnor",
    "w_a_and1",
    "w_a_not2",
    "w_b_xnor",
    "w_b_not1",
    "w_b_and2",
    "w_notb_and1",
    "w_nota_and2",
    "r_eq",
    "r_gt",
    "r_lt",
    "led_eq",
    "led_gt",
    "led_lt",
    "w_xnor_req",
    "w_req_led",
    "w_eq_gnd",
    "w_and1_rgt",
    "w_rgt_led",
    "w_gt_gnd",
    "w_and2_rlt",
    "w_rlt_led",
    "w_lt_gnd",
  ],
  highlight: "led_eq",
  activeInputs: {
    A: 1,
    B: 1,
  },
};
