import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect output wires and ground returns.",
  body: "B3 pass-through: wire from col 1, row b → r_g3 p1. Then r_g3 p2 → led_g3 anode. Each XOR output → resistor p1 → LED anode. All LED cathodes → GND rail. Apply +5 V. With all inputs LOW, all outputs should be LOW and all LEDs off.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "xor3",
    "w_b3_xor1",
    "w_b3_g3",
    "w_b2_xor1",
    "w_b2_xor2",
    "w_b1_xor2",
    "w_b1_xor3",
    "w_b0_xor3",
    "r_g3",
    "r_g2",
    "r_g1",
    "r_g0",
    "led_g3",
    "led_g2",
    "led_g1",
    "led_g0",
    "w_g3_led",
    "w_g3_gnd",
    "w_xor1_r",
    "w_g2_led",
    "w_g2_gnd",
    "w_xor2_r",
    "w_g1_led",
    "w_g1_gnd",
    "w_xor3_r",
    "w_g0_led",
    "w_g0_gnd",
  ],
  activeInputs: {
    B3: 0,
    B2: 0,
    B1: 0,
    B0: 0,
  },
};
