import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: Binary 0011 → Gray 0010.",
  body: "Set B3=0, B2=0, B1=1, B0=1. G3=0 (B3 passthrough, off), G2 = 0⊕0 = 0 (off), G1 = 0⊕1 = 1 (green ON), G0 = 1⊕1 = 0 (off). Observe that only the G1 green LED illuminates.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "xor3",
    "w_b3_xor1",
    "w_b3_g3",
    "w_b2_xor1",
    "w_b2_xor2",
    "w_b1_xor2",
    "w_b1_xor3",
    "w_b0_xor3",
    "r_g3",
    "r_g2",
    "r_g1",
    "r_g0",
    "led_g3",
    "led_g2",
    "led_g1",
    "led_g0",
    "w_g3_led",
    "w_g3_gnd",
    "w_xor1_r",
    "w_g2_led",
    "w_g2_gnd",
    "w_xor2_r",
    "w_g1_led",
    "w_g1_gnd",
    "w_xor3_r",
    "w_g0_led",
    "w_g0_gnd",
  ],
  highlight: "led_g1",
  activeInputs: {
    B3: 0,
    B2: 0,
    B1: 1,
    B0: 1,
  },
};
