import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Test: Binary 0111 → Gray 0100.",
  body: "Set B3=0, B2=1, B1=1, B0=1. G2 = 0⊕1 = 1 (yellow ON), G1 = 1⊕1 = 0 (off), G0 = 1⊕1 = 0 (off). Only the G2 yellow LED should illuminate. Compare all 8 combinations with the truth table.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "xor3",
    "w_b3_xor1",
    "w_b3_g3",
    "w_b2_xor1",
    "w_b2_xor2",
    "w_b1_xor2",
    "w_b1_xor3",
    "w_b0_xor3",
    "r_g3",
    "r_g2",
    "r_g1",
    "r_g0",
    "led_g3",
    "led_g2",
    "led_g1",
    "led_g0",
    "w_g3_led",
    "w_g3_gnd",
    "w_xor1_r",
    "w_g2_led",
    "w_g2_gnd",
    "w_xor2_r",
    "w_g1_led",
    "w_g1_gnd",
    "w_xor3_r",
    "w_g0_led",
    "w_g0_gnd",
  ],
  highlight: "led_g2",
  activeInputs: {
    B3: 0,
    B2: 1,
    B1: 1,
    B0: 1,
  },
};
