import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Test all 8 input combinations and verify outputs",
  body: "Apply all eight input combinations (A, B, Cin) from 000 to 111 in binary order. For each combination, record the state of the green LED (Sum) and red LED (Cout). Compare with the Full Adder truth table. For example: (1,1,1) should give Sum=1, Cout=1. If any discrepancy is found, use a multimeter to probe intermediate signals P, G1, G2 and isolate the fault.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "w_cin_xor2",
    "w_cin_and2",
    "w_sum1",
    "w_sum1_and2",
    "w_and1_or",
    "w_and2_or",
    "r_sum",
    "r_cout",
    "led_sum",
    "led_cout",
    "w_sum_r",
    "w_sum_led",
    "w_cout_r",
    "w_cout_led",
    "w_gnd1",
    "w_gnd2",
  ],
  highlight: "led_sum",
  activeInputs: {
    A: 1,
    B: 1,
    Cin: 1,
  },
};
