import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Measure carry ripple delay with oscilloscope",
  body: "Drive A[3:0] = 0111 and B[3:0] = 0001 with a pulse generator (A0 toggling at 1 MHz, others static). Monitor the A0 input (Ch1) and S3 output (Ch2) on the oscilloscope. The delay from A0 edge to S3 settling is the carry ripple delay through 4 stages. Measure and compare with the calculated estimate (4 × 14 ns = 56 ns for 74HC). This empirically validates the RCA timing model.",
  show: [
    "bb",
    "xor1",
    "and1",
    "xor2",
    "and2",
    "or1",
    "xor3",
    "and3",
    "xor4",
    "and4",
    "or2",
    "xor5",
    "and5",
    "xor6",
    "and6",
    "or3",
    "xor7",
    "and7",
    "xor8",
    "and8",
    "or4",
    "r_s0",
    "r_s1",
    "r_s2",
    "r_s3",
    "r_cout",
    "led_s0",
    "led_s1",
    "led_s2",
    "led_s3",
    "led_cout",
    "w_a0_xor1",
    "w_a0_and1",
    "w_b0_xor1",
    "w_b0_and1",
    "w_cin_xor2",
    "w_cin_and2",
    "w_xor1_xor2",
    "w_xor1_and2",
    "w_and1_or1",
    "w_and2_or1",
    "w_a1_xor3",
    "w_a1_and3",
    "w_b1_xor3",
    "w_b1_and3",
    "w_c1_xor4",
    "w_c1_and4",
    "w_xor3_xor4",
    "w_xor3_and4",
    "w_and3_or2",
    "w_and4_or2",
    "w_a2_xor5",
    "w_a2_and5",
    "w_b2_xor5",
    "w_b2_and5",
    "w_c2_xor6",
    "w_c2_and6",
    "w_xor5_xor6",
    "w_xor5_and6",
    "w_and5_or3",
    "w_and6_or3",
    "w_a3_xor7",
    "w_a3_and7",
    "w_b3_xor7",
    "w_b3_and7",
    "w_c3_xor8",
    "w_c3_and8",
    "w_xor7_xor8",
    "w_xor7_and8",
    "w_and7_or4",
    "w_and8_or4",
    "w_s0_r",
    "w_s0_led",
    "w_s0_gnd",
    "w_s1_r",
    "w_s1_led",
    "w_s1_gnd",
    "w_s2_r",
    "w_s2_led",
    "w_s2_gnd",
    "w_s3_r",
    "w_s3_led",
    "w_s3_gnd",
    "w_cout_r",
    "w_cout_led",
    "w_cout_gnd",
  ],
  highlight: "led_cout",
  activeInputs: {
    A0: 1,
    B0: 1,
    A1: 1,
    B1: 1,
    A2: 1,
    B2: 1,
    A3: 1,
    B3: 1,
  },
};
