import { type TheorySection } from '@/labs/lab-content.types';

export const theory: TheorySection = {
  id: "theory",
  type: "text",
  title: "Theory",
  paragraphs: [
    "Parity is the simplest form of error detection used in digital communication. An even parity generator appends a parity bit P to a data word such that the total number of 1s in the transmitted word (data + parity bit) is always even. An odd parity generator does the opposite — it ensures the total count of 1s is always odd.",
    "For a 4-bit data word B3 B2 B1 B0, the even parity bit is computed as: $$P = B_3 \\oplus B_2 \\oplus B_1 \\oplus B_0$$ The XOR operation returns 1 only when an odd number of its inputs are 1. Therefore, if the data word already has an even number of 1s, P = 0 (no correction needed); if it has an odd number of 1s, P = 1 (parity bit makes the total even).",
    "The XOR gate chain is the natural implementation: two XOR gates compute partial parities (B3⊕B2) and (B1⊕B0), and a third XOR gate combines them to produce the final parity bit. This cascaded structure scales to any word width — an n-bit parity generator requires n−1 XOR gates.",
    "Odd parity is simply the complement of even parity. It can be generated by replacing the final XOR gate with an XNOR gate, or by adding an inverter after the XOR chain output. Parity checking at the receiver re-computes the parity of the received data plus the received parity bit — if the result is non-zero (for even) or zero (for odd), a single-bit error is detected. Note that parity cannot detect two-bit errors, as two simultaneous bit flips cancel each other out.",
    "The 74HC86 quad 2-input XOR IC (CMOS, 2 V–6 V, DIP-14) is used here. Three of its four internal gates are used to implement the XOR chain. A 330 Ω current-limiting resistor protects the green output LED from excessive current.",
  ],
};
