import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Connect Q0–Q7 to resistors and LEDs.",
  body: "Wire each Q pin (on bottom bank, row f) through its 330 Ω resistor to its LED anode. Connect all eight LED cathodes to the GND rail. Connect VCC pin of the 74HC273 (pin 20, col 12 row f) to the VCC rail. Connect GND pin (pin 10, col 3 row f — note: check datasheet pin numbering) to GND rail.",
  show: [
    "bb",
    "reg8",
    "w_mr_high",
    "w_clk_reg8",
    "w_d0_reg8",
    "w_d1_reg8",
    "r_q0",
    "r_q1",
    "r_q2",
    "r_q3",
    "r_q4",
    "r_q5",
    "r_q6",
    "r_q7",
    "led_q0",
    "led_q1",
    "led_q2",
    "led_q3",
    "led_q4",
    "led_q5",
    "led_q6",
    "led_q7",
    "w_q0_r",
    "w_q1_r",
    "w_q2_r",
    "w_q3_r",
    "w_q4_r",
    "w_q5_r",
    "w_q6_r",
    "w_q7_r",
    "w_r0_led",
    "w_r1_led",
    "w_r2_led",
    "w_r3_led",
    "w_r4_led",
    "w_r5_led",
    "w_r6_led",
    "w_r7_led",
    "w_led0_gnd",
    "w_led1_gnd",
    "w_led2_gnd",
    "w_led3_gnd",
    "w_led4_gnd",
    "w_led5_gnd",
    "w_led6_gnd",
    "w_led7_gnd",
  ],
  activeInputs: {
    CLK: 0,
    D0: 0,
    D1: 0,
  },
};
