import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Load data and apply clock.",
  body: "Set D7–D0 = 1011 0100 (0xB4 = 180 decimal) using the DIP switches. Press the CLK push-button (apply a rising edge). Observe: Q7, Q5, Q4, Q2 LEDs should light up (bits that are 1 in 0xB4). Change the data inputs and clock again — outputs update immediately on the next rising edge.",
  show: [
    "bb",
    "reg8",
    "w_mr_high",
    "w_clk_reg8",
    "w_d0_reg8",
    "w_d1_reg8",
    "r_q0",
    "r_q1",
    "r_q2",
    "r_q3",
    "r_q4",
    "r_q5",
    "r_q6",
    "r_q7",
    "led_q0",
    "led_q1",
    "led_q2",
    "led_q3",
    "led_q4",
    "led_q5",
    "led_q6",
    "led_q7",
    "w_q0_r",
    "w_q1_r",
    "w_q2_r",
    "w_q3_r",
    "w_q4_r",
    "w_q5_r",
    "w_q6_r",
    "w_q7_r",
    "w_r0_led",
    "w_r1_led",
    "w_r2_led",
    "w_r3_led",
    "w_r4_led",
    "w_r5_led",
    "w_r6_led",
    "w_r7_led",
    "w_led0_gnd",
    "w_led1_gnd",
    "w_led2_gnd",
    "w_led3_gnd",
    "w_led4_gnd",
    "w_led5_gnd",
    "w_led6_gnd",
    "w_led7_gnd",
  ],
  activeInputs: {
    CLK: 1,
    D0: 0,
    D1: 0,
  },
};
