import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Count 1: CLK pulse → 0001.",
  body: "Apply one falling clock pulse. LEDs show: QA=1 (red ON), QB=QC=QD=0. Count = 1.",
  show: [
    "bb",
    "ctr",
    "w_clk_ctr",
    "w_qa_clkb",
    "w_qa_r01",
    "w_qc_r02",
    "r_qa",
    "led_qa",
    "r_qb",
    "led_qb",
    "r_qc",
    "led_qc",
    "r_qd",
    "led_qd",
    "w_qa_out",
    "w_qa_led",
    "w_qa_gnd",
    "w_qb_out",
    "w_qb_led",
    "w_qb_gnd",
    "w_qc_out",
    "w_qc_led",
    "w_qc_gnd",
    "w_qd_out",
    "w_qd_led",
    "w_qd_gnd",
  ],
  activeInputs: {
    CLK: 1,
  },
};
