import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Count 4: CLK pulse → 0100.",
  body: "Fourth pulse. QB=0, QC=1. Count = 4. Yellow OFF, Green ON.",
  show: [
    "bb",
    "ctr",
    "w_clk_ctr",
    "w_qa_clkb",
    "w_qa_r01",
    "w_qc_r02",
    "r_qa",
    "led_qa",
    "r_qb",
    "led_qb",
    "r_qc",
    "led_qc",
    "r_qd",
    "led_qd",
    "w_qa_out",
    "w_qa_led",
    "w_qa_gnd",
    "w_qb_out",
    "w_qb_led",
    "w_qb_gnd",
    "w_qc_out",
    "w_qc_led",
    "w_qc_gnd",
    "w_qd_out",
    "w_qd_led",
    "w_qd_gnd",
  ],
  activeInputs: {
    CLK: 0,
  },
};
