import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Test all 4 input combinations and verify one-hot output",
  body: "Apply each of the four input combinations (A,B): (0,0), (0,1), (1,0), (1,1). For (0,0): only LED0 (Y0) should be ON. For (0,1): only LED1 (Y1) should be ON. For (1,0): only LED2 (Y2) should be ON. For (1,1): only LED3 (Y3) should be ON. Confirm the one-hot property: exactly one LED lit at a time. Record all observations. Use a multimeter to verify output logic levels at each AND gate output.",
  show: [
    "bb",
    "not_a",
    "not_b",
    "and0",
    "and1",
    "and2",
    "and3",
    "w_a_na",
    "w_b_nb",
    "w_na_and0",
    "w_nb_and0",
    "w_na_and1",
    "w_b_and1",
    "w_a_and2",
    "w_nb_and2",
    "w_a_and3",
    "w_b_and3",
    "r0",
    "r1",
    "r2",
    "r3",
    "led0",
    "led1",
    "led2",
    "led3",
    "w_y0_r",
    "w_y0_led",
    "w_y1_r",
    "w_y1_led",
    "w_y2_r",
    "w_y2_led",
    "w_y3_r",
    "w_y3_led",
    "w_g0",
    "w_g1",
    "w_g2",
    "w_g3",
  ],
  highlight: "led2",
  activeInputs: {
    A: 1,
    B: 0,
  },
};
