import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect internal logic cascaded paths and complete LED drive lines.",
  body:
    "Connect white jumper wires for internal sub-expressions: " +
    "T = C + D from or_cd.Y to and_b_t.B and xor_x.B; " +
    "B·T from and_b_t.Y to or_w.B; and C ⊕ D from xor_cd.Y to not_y.A. " +
    "Wire gate outputs to their respective 330 Ω resistors, connect resistors to LED anodes, " +
    "and return all LED cathodes to the bottom ground rail using black wires.",
  show: [
    "bb",
    "psu",
    "w_rail_link",
    "or_cd",
    "and_b_t",
    "or_w",
    "xor_x",
    "xor_cd",
    "not_y",
    "not_z",
    "w_vcc_or_cd",
    "w_gnd_or_cd",
    "w_vcc_and",
    "w_gnd_and",
    "w_vcc_or_w",
    "w_gnd_or_w",
    "w_vcc_xor_x",
    "w_gnd_xor_x",
    "w_vcc_xor_cd",
    "w_gnd_xor_cd",
    "w_vcc_not_y",
    "w_gnd_not_y",
    "w_vcc_not_z",
    "w_gnd_not_z",
    "r_w",
    "led_w",
    "r_x",
    "led_x",
    "r_y",
    "led_y",
    "r_z",
    "led_z",
    "w_a_or_w",
    "w_b_and",
    "w_b_xor",
    "w_c_or",
    "w_c_xor",
    "w_d_or",
    "w_d_xor",
    "w_d_not",
    "w_or_cd_to_and",
    "w_or_cd_to_xor",
    "w_and_to_or_w",
    "w_xor_cd_to_not_y",
    "w_w_to_r",
    "w_r_to_led_w",
    "w_gnd_w",
    "w_x_to_r",
    "w_r_to_led_x",
    "w_gnd_x",
    "w_y_to_r",
    "w_r_to_led_y",
    "w_gnd_y",
    "w_z_to_r",
    "w_r_to_led_z",
    "w_gnd_z",
  ],
  activeInputs: {
    A: 0,
    B: 0,
    C: 0,
    D: 0,
  },
};
