import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test BCD = 0101 (decimal 5).",
  body:
    "Set inputs A=0, B=1, C=0, D=1. Excess-3 code conversion yields: 5 + 3 = 8 (binary 1000₂), " +
    "so W=1, X=0, Y=0, Z=0. Verify that only the MSB LED (W, red) illuminates.",
  show: [
    "bb",
    "psu",
    "w_rail_link",
    "or_cd",
    "and_b_t",
    "or_w",
    "xor_x",
    "xor_cd",
    "not_y",
    "not_z",
    "w_vcc_or_cd",
    "w_gnd_or_cd",
    "w_vcc_and",
    "w_gnd_and",
    "w_vcc_or_w",
    "w_gnd_or_w",
    "w_vcc_xor_x",
    "w_gnd_xor_x",
    "w_vcc_xor_cd",
    "w_gnd_xor_cd",
    "w_vcc_not_y",
    "w_gnd_not_y",
    "w_vcc_not_z",
    "w_gnd_not_z",
    "r_w",
    "led_w",
    "r_x",
    "led_x",
    "r_y",
    "led_y",
    "r_z",
    "led_z",
    "w_a_or_w",
    "w_b_and",
    "w_b_xor",
    "w_c_or",
    "w_c_xor",
    "w_d_or",
    "w_d_xor",
    "w_d_not",
    "w_or_cd_to_and",
    "w_or_cd_to_xor",
    "w_and_to_or_w",
    "w_xor_cd_to_not_y",
    "w_w_to_r",
    "w_r_to_led_w",
    "w_gnd_w",
    "w_x_to_r",
    "w_r_to_led_x",
    "w_gnd_x",
    "w_y_to_r",
    "w_r_to_led_y",
    "w_gnd_y",
    "w_z_to_r",
    "w_r_to_led_z",
    "w_gnd_z",
  ],
  highlight: "led_w",
  activeInputs: {
    A: 0,
    B: 1,
    C: 0,
    D: 1,
  },
};
