import { type ComponentInstance } from "@/labs/types";
export const components: ComponentInstance[] = [
  { id: "bb", type: "breadboard" },
  {
    id: "r1",
    type: "resistor",
    ohms: 1000,
    mountedAt: { board: "bb", col: 3, row: "c" },
  },
  {
    id: "r2",
    type: "resistor",
    ohms: 2200,
    mountedAt: { board: "bb", col: 3, row: "h" },
  },
  {
    id: "r_load",
    type: "resistor",
    ohms: 3300,
    mountedAt: { board: "bb", col: 10, row: "c" },
  },
  {
    id: "led1",
    type: "led",
    color: "red",
    mountedAt: { board: "bb", col: 15, row: "c" },
  },
  {
    id: "w_vcc_r1",
    type: "wire",
    color: "red",
    from: { board: "bb", rail: "vcc_top", col: 3 },
    to: { component: "r1", end: "p1" },
  },
  {
    id: "w_vcc_r2",
    type: "wire",
    color: "red",
    from: { board: "bb", rail: "vcc_top", col: 1 },
    to: { component: "r2", end: "p1" },
  },
  {
    id: "w_r1_junc",
    type: "wire",
    color: "orange",
    from: { component: "r1", end: "p2" },
    to: { board: "bb", col: 8, row: "c" },
  },
  {
    id: "w_r2_junc",
    type: "wire",
    color: "orange",
    from: { component: "r2", end: "p2" },
    to: { board: "bb", col: 8, row: "h" },
  },
  {
    id: "w_junc_link",
    type: "wire",
    color: "white",
    from: { board: "bb", col: 8, row: "d" },
    to: { board: "bb", col: 8, row: "g" },
  },
  {
    id: "w_junc_rload",
    type: "wire",
    color: "green",
    from: { board: "bb", col: 8, row: "b" },
    to: { component: "r_load", end: "p1" },
  },
  {
    id: "w_rload_led",
    type: "wire",
    color: "green",
    from: { component: "r_load", end: "p2" },
    to: { led: "led1", end: "anode" },
  },
  {
    id: "w_led_gnd",
    type: "wire",
    color: "black",
    from: { led: "led1", end: "cathode" },
    to: { board: "bb", rail: "gnd_top", col: 16 },
  },
];
