import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Place 330 Ω resistors and LEDs.",
  body: "Place r_w (col 22, row c) and r_x (col 22, row h). Place r_y (col 28, row c) and r_z (col 28, row h). Mount LEDs: led_w red (col 26, row c), led_x yellow (col 26, row h), led_y green (col 32, row c), led_z blue (col 32, row h).",
  show: [
    "bb",
    "not1",
    "not2",
    "and1",
    "and2",
    "or1",
    "or2",
    "xor1",
    "w_a_or1",
    "w_b_and1",
    "w_b_and2",
    "w_b_or2",
    "w_c_and1",
    "w_c_xor1",
    "w_d_and2",
    "w_d_not1",
    "w_d_not2",
    "w_d_xor1",
    "w_and1_or1",
    "w_and2_or2",
    "r_w",
    "r_x",
    "r_y",
    "r_z",
    "led_w",
    "led_x",
    "led_y",
    "led_z",
  ],
  activeInputs: {
    A: 0,
    B: 0,
    C: 0,
    D: 0,
  },
};
