import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect output wires and ground returns.",
  body: "Connect each gate output to its resistor p1. Connect each resistor p2 to its LED anode. Connect all LED cathodes to the GND rail with black wires. Apply +5 V to VCC rail. Verify all ICs have VCC on pin 14 and GND on pin 7.",
  show: [
    "bb",
    "not1",
    "not2",
    "and1",
    "and2",
    "or1",
    "or2",
    "xor1",
    "w_a_or1",
    "w_b_and1",
    "w_b_and2",
    "w_b_or2",
    "w_c_and1",
    "w_c_xor1",
    "w_d_and2",
    "w_d_not1",
    "w_d_not2",
    "w_d_xor1",
    "w_and1_or1",
    "w_and2_or2",
    "r_w",
    "r_x",
    "r_y",
    "r_z",
    "led_w",
    "led_x",
    "led_y",
    "led_z",
    "w_or1_r",
    "w_w_led",
    "w_w_gnd",
    "w_or2_r",
    "w_x_led",
    "w_x_gnd",
    "w_xor1_r",
    "w_y_led",
    "w_y_gnd",
    "w_not2_r",
    "w_z_led",
    "w_z_gnd",
  ],
  activeInputs: {
    A: 0,
    B: 0,
    C: 0,
    D: 0,
  },
};
