import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Test BCD = 0101 (decimal 5).",
  body: "Set A=0, B=1, C=0, D=1 using the DIP switch. Expected XS3 output = 1000 (decimal 8). Only the W LED (red) should illuminate. Verify: 5 + 3 = 8 = 1000₂.",
  show: [
    "bb",
    "not1",
    "not2",
    "and1",
    "and2",
    "or1",
    "or2",
    "xor1",
    "w_a_or1",
    "w_b_and1",
    "w_b_and2",
    "w_b_or2",
    "w_c_and1",
    "w_c_xor1",
    "w_d_and2",
    "w_d_not1",
    "w_d_not2",
    "w_d_xor1",
    "w_and1_or1",
    "w_and2_or2",
    "r_w",
    "r_x",
    "r_y",
    "r_z",
    "led_w",
    "led_x",
    "led_y",
    "led_z",
    "w_or1_r",
    "w_w_led",
    "w_w_gnd",
    "w_or2_r",
    "w_x_led",
    "w_x_gnd",
    "w_xor1_r",
    "w_y_led",
    "w_y_gnd",
    "w_not2_r",
    "w_z_led",
    "w_z_gnd",
  ],
  highlight: "led_w",
  activeInputs: {
    A: 0,
    B: 1,
    C: 0,
    D: 1,
  },
};
