import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test all 8 input combinations",
  body: "Apply all eight input combinations (A, B, Bin) from 000 to 111. For each combination record the Difference LED (green) and Borrow-out LED (red) states. Compare with the Full Subtractor truth table. Key cases: (0,1,0) → D=1, Bout=1; (0,0,1) → D=1, Bout=1; (1,1,1) → D=1, Bout=1; (1,0,0) → D=1, Bout=0. Document any discrepancies and troubleshoot with a probe.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "not1",
    "and1",
    "and2",
    "and3",
    "or1",
    "or2",
    "w_a_xor1",
    "w_b_xor1",
    "w_bin_xor2",
    "w_d1_xor2",
    "w_a_not",
    "w_nota_and1",
    "w_b_and1",
    "w_nota_and2",
    "w_bin_and2",
    "w_b_and3",
    "w_bin_and3",
    "w_and1_or1",
    "w_and2_or1",
    "w_or1_or2",
    "w_and3_or2",
    "r_diff",
    "r_bout",
    "led_diff",
    "led_bout",
    "w_diff_r",
    "w_diff_led",
    "w_bout_r",
    "w_bout_led",
    "w_gnd1",
    "w_gnd2",
  ],
  highlight: "led_bout",
  activeInputs: {
    A: 0,
    B: 1,
    Bin: 0,
  },
};
