import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Wire B inputs through XOR inverters.",
  body: "Blue wires from row b: col 1 → xor_b1 pin A, col 2 → xor_b2 pin A, col 3 → xor_b3 pin A, col 4 → xor_b4 pin A. White wires from each XOR output to the adder b-pins: xor_b1.Y → b1, etc. B is the subtrahend; it is inverted before entering the adder.",
  show: [
    "bb",
    "xor_b1",
    "xor_b2",
    "xor_b3",
    "xor_b4",
    "w_vcc_xb1",
    "w_vcc_xb2",
    "w_vcc_xb3",
    "w_vcc_xb4",
    "adder_sub",
    "w_c0_vcc",
    "w_a1_adder_sub",
    "w_a2_adder_sub",
    "w_a3_adder_sub",
    "w_a4_adder_sub",
    "w_b1_xor",
    "w_b2_xor",
    "w_b3_xor",
    "w_b4_xor",
    "w_xb1_adder",
    "w_xb2_adder",
    "w_xb3_adder",
    "w_xb4_adder",
  ],
  activeInputs: {
    A4: 1,
    A3: 0,
    A2: 0,
    A1: 0,
    B4: 0,
    B3: 1,
    B2: 0,
    B1: 1,
  },
};
