import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Wire output LEDs and test.",
  body: "Wire five LED paths for S1–S4 and C4 to the GND rail via 330 Ω resistors. Apply +5 V. With A=B, the result should be 0000 with C4=1 (borrow cleared). Verify the LED pattern represents the correct difference.",
  show: [
    "bb",
    "xor_b1",
    "xor_b2",
    "xor_b3",
    "xor_b4",
    "w_vcc_xb1",
    "w_vcc_xb2",
    "w_vcc_xb3",
    "w_vcc_xb4",
    "adder_sub",
    "w_c0_vcc",
    "w_a1_adder_sub",
    "w_a2_adder_sub",
    "w_a3_adder_sub",
    "w_a4_adder_sub",
    "w_b1_xor",
    "w_b2_xor",
    "w_b3_xor",
    "w_b4_xor",
    "w_xb1_adder",
    "w_xb2_adder",
    "w_xb3_adder",
    "w_xb4_adder",
    "r_s1",
    "r_s2",
    "r_s3",
    "r_s4",
    "r_c4",
    "led_s1",
    "led_s2",
    "led_s3",
    "led_s4",
    "led_c4",
    "w_s1_r",
    "w_s1_led",
    "w_s1_gnd",
    "w_s2_r",
    "w_s2_led",
    "w_s2_gnd",
    "w_s3_r",
    "w_s3_led",
    "w_s3_gnd",
    "w_s4_r",
    "w_s4_led",
    "w_s4_gnd",
    "w_c4_r",
    "w_c4_led",
    "w_c4_gnd",
  ],
  activeInputs: {
    A4: 1,
    A3: 0,
    A2: 0,
    A1: 0,
    B4: 0,
    B3: 1,
    B2: 0,
    B1: 1,
  },
};
