import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Assemble Phase B — Voltage-Divider Bias circuit.",
  body: "Insert $R_1 = 100\\,\\text{k}\\Omega$ at col 15–18, row c; wire VCC → $R_1$ (red). Insert $R_2 = 10\\,\\text{k}\\Omega$ at col 15–18, row h; wire $R_2$ bottom → GND (black). Insert $R_{C2} = 4.7\\,\\text{k}\\Omega$ at col 20–23, row c; wire VCC → $R_{C2}$ (red). Insert $R_E = 1\\,\\text{k}\\Omega$ at col 20–23, row h; wire $R_E$ bottom → GND (black). Insert green LED at col 25–26; wire $R_{C2}$ → LED anode (green); LED cathode → GND.",
  show: [
    "bb",
    "psu",
    "w_vcc_rb",
    "dmm",
    "w_amm_in",
    "w_amm_out",
    "r_b",
    "r_c1",
    "led_a",
    "w_vcc_rc1",
    "w_rc1_leda",
    "w_leda_gnd",
    "r1",
    "r2",
    "r_c2",
    "r_e",
    "led_b",
    "w_vcc_r1",
    "w_r2_gnd",
    "w_vcc_rc2",
    "w_re_gnd",
    "w_rc2_ledb",
    "w_ledb_gnd",
  ],
  highlight: "r1",
};
