import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test blanking and latch functions",
  body: "Pull BL' (pin 4) to GND momentarily — all segments should extinguish (blank display), confirming the blanking function. Restore BL' to +5 V. Now set LE (pin 5) HIGH (latch enable): the display should hold the currently displayed digit even if the input switches are changed. Change the BCD input to a different digit — the display should remain unchanged. Pull LE LOW again to return to transparent (real-time) mode. Document the latch behaviour.",
  show: [
    "bb",
    "led_a",
    "led_b",
    "led_c",
    "led_d",
    "led_e",
    "led_f",
    "led_g",
    "r_a",
    "r_b",
    "r_c",
    "r_d",
    "r_e",
    "r_f",
    "r_g",
    "w_vcc_ra",
    "w_vcc_rb",
    "w_vcc_rc",
    "w_vcc_rd",
    "w_vcc_re",
    "w_vcc_rf",
    "w_vcc_rg",
    "w_ra_leda",
    "w_rb_ledb",
    "w_rc_ledc",
    "w_rd_ledd",
    "w_re_lede",
    "w_rf_ledf",
    "w_rg_ledg",
  ],
};
