import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Wire outputs Y0–Y3 to LEDs.",
  body: "Y0 (col 10 row e) → r_y0 (col 18 row c) → led_y0 red → GND. Y1 (col 11 row e) → r_y1 (col 18 row h) → led_y1 yellow → GND. Y2 (col 12 row e) → r_y2 (col 25 row c) → led_y2 green → GND. Y3 (col 13 row e) → r_y3 (col 25 row h) → led_y3 blue → GND. Apply +5 V. All LEDs off initially (outputs all HIGH when nothing selected — wait, AB=00 selects Y0, so red LED should be ON at power-up).",
  show: [
    "bb",
    "demux14",
    "w_en_gnd",
    "w_a_demux14",
    "w_b_demux14",
    "r_y0",
    "r_y1",
    "r_y2",
    "r_y3",
    "led_y0",
    "led_y1",
    "led_y2",
    "led_y3",
    "w_y0_r",
    "w_y0_led",
    "w_y0_gnd",
    "w_y1_r",
    "w_y1_led",
    "w_y1_gnd",
    "w_y2_r",
    "w_y2_led",
    "w_y2_gnd",
    "w_y3_r",
    "w_y3_led",
    "w_y3_gnd",
  ],
  activeInputs: {
    A: 0,
    B: 0,
  },
};
