import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Test A=0, B=0 → Y0 active.",
  body: "Set A=0, B=0 using the DIP switch. Y0 goes LOW; red LED lights. Y1, Y2, Y3 remain HIGH; yellow, green, blue LEDs are off. Confirm that exactly one LED is on at a time.",
  show: [
    "bb",
    "demux14",
    "w_en_gnd",
    "w_a_demux14",
    "w_b_demux14",
    "r_y0",
    "r_y1",
    "r_y2",
    "r_y3",
    "led_y0",
    "led_y1",
    "led_y2",
    "led_y3",
    "w_y0_r",
    "w_y0_led",
    "w_y0_gnd",
    "w_y1_r",
    "w_y1_led",
    "w_y1_gnd",
    "w_y2_r",
    "w_y2_led",
    "w_y2_gnd",
    "w_y3_r",
    "w_y3_led",
    "w_y3_gnd",
  ],
  highlight: "led_y0",
  activeInputs: {
    A: 0,
    B: 0,
  },
};
