import { type TheorySection } from '@/labs/lab-content.types';

export const theory: TheorySection = {
  id: "theory",
  type: "text",
  title: "Theory",
  paragraphs: [
    "A combinational array multiplier computes the product of two n-bit unsigned binary numbers using a rectangular array of AND gates for partial product generation and a cascade of adder rows for partial product summation. The result is a 2n-bit product available combinationally (after a fixed propagation delay) with no clock cycles required.",
    "For two n-bit unsigned numbers $A = A_{n-1} \\ldots A_1 A_0$ and $B = B_{n-1} \\ldots B_1 B_0$, the partial product bit $PP_{ij} = A_i \\cdot B_j$ is generated by a single AND gate. There are $n^2$ AND gates in total. Each partial product $PP_j$ (= $A \\cdot B_j$) is an n-bit row that must be added to the previous accumulated sum, shifted left by j positions.",
    "The adder array structure: Row 0: PP0 is the first partial product (no addition needed). Row 1: PP0 + PP1 using a row of half adders (LSB) and full adders. Row 2: (Row 1 result) + PP2 using full adders. Row k: (Row k-1 result) + PPk. The final row produces the 2n-bit product. Total gate complexity: O(n²) AND gates and O(n²) adder gates.",
    "For a 4×4 array multiplier, the structure uses: 16 AND gates (partial products), 4 half adders, and 8 full adders organized in 3 adder rows. The result is an 8-bit product with propagation delay O(n) gate levels.",
    "Signed multiplication (2's complement) requires modification. The Baugh-Wooley algorithm handles sign bits specially: for inputs A and B in 2's complement, the MSB has a negative weight ($-2^{n-1}$). The Baugh-Wooley array modifies the partial product generation for sign bits, inverting certain AND gate outputs and correcting with added constants, producing a correct signed product without a separate sign-extension step.",
    "Comparison: Unsigned array multiplier: $n^2$ AND + O(n²) FA, delay O(n). Signed Baugh-Wooley: same gate count with different connections, delay O(n). Both have O(n²) area and O(n) delay — slower than Wallace tree (O(log n)) but simpler to design and lay out in VLSI (regular, rectangular structure suitable for systematic place-and-route).",
  ],
};
