import { type SceneProcedureStep } from '@/labs/experiments/types';

export const step: SceneProcedureStep = {
  label: "Wire output LEDs S1–S4 and C4.",
  body: "Five output paths. S1 (col 10, row e) → r_s1 (col 22, c) → led_s1 red. S2 (col 7, row e) → r_s2 (col 22, h) → led_s2 yellow. S3 (col 12, row f) → r_s3 (col 29, c) → led_s3 green. S4 (col 9, row f) → r_s4 (col 29, h) → led_s4 blue. C4 (col 8, row f) → r_c4 (col 36, c) → led_c4 white. All cathodes to GND.",
  show: [
    "bb",
    "adder",
    "w_c0_gnd",
    "w_a1_adder",
    "w_a2_adder",
    "w_a3_adder",
    "w_a4_adder",
    "w_b1_adder",
    "w_b2_adder",
    "w_b3_adder",
    "w_b4_adder",
    "r_s1",
    "r_s2",
    "r_s3",
    "r_s4",
    "r_c4",
    "led_s1",
    "led_s2",
    "led_s3",
    "led_s4",
    "led_c4",
    "w_s1_r",
    "w_s1_led",
    "w_s1_gnd",
    "w_s2_r",
    "w_s2_led",
    "w_s2_gnd",
    "w_s3_r",
    "w_s3_led",
    "w_s3_gnd",
    "w_s4_r",
    "w_s4_led",
    "w_s4_gnd",
    "w_c4_r",
    "w_c4_led",
    "w_c4_gnd",
  ],
  activeInputs: {
    A4: 0,
    A3: 0,
    A2: 1,
    A1: 1,
    B4: 0,
    B3: 1,
    B2: 0,
    B1: 1,
    C0: 0,
  },
};
