import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: 7 + 9 = 16.",
  body: "Set A=0111 (A3=A2=A1=1) and B=1001 (B4=B1=1). Expected: 5-bit result 10000. S4=S3=S2=S1=0 (all sum LEDs off), C4=1 (white LED ON). The carry indicates the 4-bit result overflowed.",
  show: [
    "bb",
    "adder",
    "w_c0_gnd",
    "w_a1_adder",
    "w_a2_adder",
    "w_a3_adder",
    "w_a4_adder",
    "w_b1_adder",
    "w_b2_adder",
    "w_b3_adder",
    "w_b4_adder",
    "r_s1",
    "r_s2",
    "r_s3",
    "r_s4",
    "r_c4",
    "led_s1",
    "led_s2",
    "led_s3",
    "led_s4",
    "led_c4",
    "w_s1_r",
    "w_s1_led",
    "w_s1_gnd",
    "w_s2_r",
    "w_s2_led",
    "w_s2_gnd",
    "w_s3_r",
    "w_s3_led",
    "w_s3_gnd",
    "w_s4_r",
    "w_s4_led",
    "w_s4_gnd",
    "w_c4_r",
    "w_c4_led",
    "w_c4_gnd",
  ],
  highlight: "led_c4",
  activeInputs: {
    A4: 0,
    A3: 1,
    A2: 1,
    A1: 1,
    B4: 1,
    B3: 0,
    B2: 0,
    B1: 1,
    C0: 0,
  },
};
