/**
 * Runs in Node at build time (and dev start), NOT in the browser.
 * Reads your already-assembled experiment data and writes a flat,
 * pre-computed SearchIndexEntry[] to disk as a plain .ts data file.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

import { ALL_EXPERIMENTS } from "../src/sections/explore/explore.data";
import { ALL_CONTENTS } from "../src/labs/content";
import {
  buildSearchIndex,
  type ContentLookup,
} from "../src/sections/explore/search-index.build";
import {
  type TheorySection,
  type ProcedureSection,
  type ApparatusSection,
} from "../src/labs/lab-content.types";

const getContent: ContentLookup = (circuitId) => {
  const content = ALL_CONTENTS[circuitId as keyof typeof ALL_CONTENTS] as any;
  if (!content) return undefined;

  const theory = (
    content.sections.filter((s: any) => s.type === "text") as TheorySection[]
  ).flatMap((s) => s.paragraphs);

  const procedure = (
    content.sections.filter(
      (s: any) => s.type === "procedure",
    ) as ProcedureSection[]
  ).flatMap((s) => s.steps.map((step) => step.body));

  const apparatus = (
    content.sections.filter(
      (s: any) => s.type === "apparatus",
    ) as ApparatusSection[]
  ).flatMap((s) => s.items.map((item) => item.name));

  return { theory, procedure, apparatus };
};

const index = buildSearchIndex(ALL_EXPERIMENTS, getContent);

const outDir = path.join(process.cwd(), "src/sections/explore");
const outFile = path.join(outDir, "search-index.output.ts");

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/build-search-index.ts — do not edit by hand.\n` +
    `// Regenerated on every \`npm run dev\` / \`npm run build\`.\n\n` +
    `import { type SearchIndexEntry } from './search-index.types';\n\n` +
    `export const SEARCH_INDEX: SearchIndexEntry[] = ${JSON.stringify(index, null, 2)};\n`,
);

console.log(
  `[search-index] wrote ${index.length} entries → ${path.relative(process.cwd(), outFile)}`,
);
